NUKnightLab/storyline

src/js/slider.js
src/scss/_line.scss
src/scss/_slider.scss
src/scss/_variables.scss

I made changes so that the card animates into the active state.
@shortdiv it looks like the `is-animating` class is being removed too soon so the animation of the card moving into place never completes, it just sort of jumps into place.

Style animation tweaks

---

src/js/chart.js
src/js/slider.js
src/js/storyline.js
src/scss/_slider.scss

This fixes the height issue that we were facing where the cards are bumping up against the nav dots. It also addresses the width issue in ios where the slider view was spanning past the width of the viewport by giving slider view a specific width.

Setting height via js

---

src/assets/data.json
src/js/chart.js
src/js/data.js

Eliminate moment

---

src/js/chart.js
src/js/slider.js
src/scss/_chart.scss
src/scss/_line.scss
src/scss/_slider.scss
src/scss/_storyline.scss
src/scss/storyline.scss

Connect markers and slider

---

src/js/data.js

fix: Adding error basic handler that prints error message to page

---

src/js/chart.js
src/js/slider.js
src/js/storyline.js
src/scss/_line.scss

fix: Reordering svg elements so text is above marker dots

---

src/scss/_colors.scss
src/scss/_line.scss
src/scss/_slider.scss

fix: Remove important and adding darker grey to colors

---

src/scss/_slider.scss

fix: Adding min height to card header and reorganizing sass

---

src/js/slider.js

support swipes through hammerjs #30

---

src/js/chart.js

fix: Adding space for y axis

---

src/assets/data.json
src/js/data.js
src/js/slider.js
src/js/storyline.js

Work that needed to get done, so cards can be read either from json or from spreadsheets

Reading cards from sheets+ declaratively in json works

---

src/js/slider.js

Swipe is a duplicate action that gets called, so might as well have pan handle swiping cards instead of having to replicate code. 
The friction can be reduced by reducing the hard coded number (0.5) in the pan case. As was discussed, the card moves when it is well past the midpoint of the screen.

fix: Reworking card pan for legibility and enabling pan to handle swipe

---

src/js/chart.js
src/js/slider.js
src/js/storyline.js
src/scss/_line.scss
src/scss/_slider.scss

Line now drags with the card drag.
The animation on end drag is snappy despite the css animation. I imagine I'd have to use a translate to move the line more naturally, but since this is a line svg element, it would probably require a rotation along the marker. So something like 
```
transform-origin: markerX markerY;
transform: rotate(?deg);
```
The calculation for the rotation requires some trigonometry that to me seems too complex for what we want. So open to suggestions on this.

Creating line animation

---

src/scss/_slider.scss

Adds equal padding to card text

fix: Equalizing padding on card text

---

package.json
src/js/chart.js
src/js/slider.js
src/js/storyline.js
src/scss/_line.scss
webpack.config.js

Reworked analytics work into updated code

Including analytics tracker

---

src/js/slider.js
src/js/storyline.js

Fixed issue with marker elements not activating click

fix: Passing in marker div elements instead of static data markers

---

src/js/slider.js

Can I have 👀 on this to make sure that this fixes the panning issue? #68

fix: Missing variable that was causing panning issue

---

src/js/slider.js

This seems to address the issue raised in #69 but would appreciate more eyes before merging.

attempt to implement maxwidth of cards on small displays, re #69

---

src/js/data.js
test/data-test.js

Fixes breaking condition when data value is 0

fix: falsy conditional

---

src/js/data.js
src/js/slider.js

fix: Make card date an immutable so it is accessible after resize
